cc_test(
	name = "tests",
	srcs = glob(["**/*.cc"]),
	deps = [
		"//src/lib:SolutionLib",
		"@googletest//:gtest_main" # @googletest <- from the repo. of googletest / gtest_main <- use this target
	]
)
